name: Deploy Supabase Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      # --- THIS IS THE OFFICIAL, CORRECTED METHOD ---
      # It installs the Supabase CLI using npm, which is the standard way.
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install supabase --save-dev
      # --- END OF CORRECTED METHOD ---

      - name: Deploy Supabase functions
        # Use npx to run the locally installed CLI
        run: npx supabase functions deploy --project-ref $SUPABASE_PROJECT_ID